services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"